[package]
name = "gawr"
version = "1.0.3"
license = "MIT OR Apache-2.0"
authors = ["Nicolas Mémeint <nicomem@pm.me>"]
repository = "https://github.com/nicomem/gawr"
edition = "2021"
include = ["src/**/*", "CHANGELOG.md"]
description = "An audio archiver tool to create an audio library out of web videos. Download, clip, and normalize audio streams"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
clap = { version = "4.0.8", features = ["cargo"] }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
crossbeam-channel = "0.5.2"
fastrand = "1.7.0"
heck = "0.4.0"
indoc = "2.0.0"
miette = { version = "5.1.1", features = ["fancy"] }
once_cell = "1.9.0"
owo-colors = "3.3.0"
regex = "1.5.4"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.78"
tempfile = "3.3.0"
time = { version = "0.3.9", features = ["local-offset"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["time"] }

[features]

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
