[package]
name = "gawr"
version = "0.6.0"
edition = "2021"
include = ["src/**/*", "CHANGELOG.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bitflags = "1.3.2"
clap = { version = "3.1.2", features = ["derive", "env"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
fastrand = "1.7.0"
heck = "0.4.0"
log = "0.4.14"
once_cell = "1.9.0"
rayon-core = "1.9.1"
regex = "1.5.4"
serde_json = "1.0.78"
tempfile = "3.3.0"
thiserror = "1.0.30"

[features]

[profile.release]
lto = true
strip = true
opt-level = "z"
