[package]
name = "gawr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
convert_case = "0.5.0"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
rayon = "1.5.1"
regex = "1.5.4"
serde_json = "1.0.78"

[features]
